services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env  
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"